/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.AssignmentGrades;
import Model.Course;
import Model.ExamGrades;
import Model.Instructor;
import Model.Lecturer;
import Model.Postgraduate;
import Model.Subject;
import Model.Undergraduate;
import static View.EnrollementSystemHome.hm;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asitha
 */
public class AdministratorHome extends javax.swing.JFrame {
    public static Undergraduate unG;
    public static Postgraduate posG;
    public static Subject sub;
    public static Course CS;
    public static Instructor ins;
    public static Lecturer lec;
    public static ExamGrades exm;
    public static AssignmentGrades asm;
    public static AdministratorUndergraduateUpdate unGup;
    public static AdministratorPostgraduateUpdate posGup;
    public static AdministratorSubjectsUpdate subUp;
    public static AdministratorExamUpdate exmUp;
    public static AdministratorTimeAllocation time;
    public static AdministratotLocationUpdate adLoc;
    public static AdministratorAssignmentUpdate adAsUp;
    public static AdministratorCourseUpdate adCsUp;
    public static AdministratorLecturerUpdate adLecUp;
    public static AdministratorInstructorUpdate adInUp;
    
    
    /**
     * Creates new form AdministratotProfile
     */
    public AdministratorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        postgraduateLbl = new javax.swing.JLabel();
        undergraduateLbl = new javax.swing.JLabel();
        calendarLbl = new javax.swing.JLabel();
        registerLbl = new javax.swing.JLabel();
        instructorLbl = new javax.swing.JLabel();
        lecturerLbl = new javax.swing.JLabel();
        locationsLbl = new javax.swing.JLabel();
        teachingAllocationLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        examinationLbl = new javax.swing.JLabel();
        subjectLbl = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        assignmentLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrator Panel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setOpaque(true);

        postgraduateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/postBtns.png"))); // NOI18N
        postgraduateLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postgraduateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postgraduateLblMouseClicked(evt);
            }
        });

        undergraduateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/underBtn.png"))); // NOI18N
        undergraduateLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undergraduateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undergraduateLblMouseClicked(evt);
            }
        });

        calendarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar.png"))); // NOI18N
        calendarLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarLblMouseClicked(evt);
            }
        });

        registerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.png"))); // NOI18N
        registerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLblMouseClicked(evt);
            }
        });

        instructorLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insBtns.png"))); // NOI18N
        instructorLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructorLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructorLblMouseClicked(evt);
            }
        });

        lecturerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lecBtns.png"))); // NOI18N
        lecturerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lecturerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerLblMouseClicked(evt);
            }
        });

        locationsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locationBtn.png"))); // NOI18N
        locationsLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        locationsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationsLblMouseClicked(evt);
            }
        });

        teachingAllocationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timeAllocationBtn.png"))); // NOI18N
        teachingAllocationLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teachingAllocationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachingAllocationLblMouseClicked(evt);
            }
        });

        courseLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coursesBtn.png"))); // NOI18N
        courseLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        courseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseLblMouseClicked(evt);
            }
        });

        examinationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/examsBtn.png"))); // NOI18N
        examinationLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examinationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examinationLblMouseClicked(evt);
            }
        });

        subjectLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subjectBtn.png"))); // NOI18N
        subjectLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectLblMouseClicked(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        closeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        jLabel14.setText("Administrator Panel");

        assignmentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assignmentsBtn.png"))); // NOI18N
        assignmentLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignmentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(postgraduateLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(undergraduateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calendarLbl)
                                    .addGap(5, 5, 5)
                                    .addComponent(assignmentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(examinationLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(locationsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2)
                                            .addComponent(subjectLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(teachingAllocationLbl))
                                        .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lecturerLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instructorLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(courseLbl)))
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postgraduateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(undergraduateLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignmentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(instructorLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lecturerLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examinationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachingAllocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(courseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void postgraduateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postgraduateLblMouseClicked
        
        posGup=new AdministratorPostgraduateUpdate();
        posGup.setVisible(true);
        posGup.setLocationRelativeTo(null);

    }//GEN-LAST:event_postgraduateLblMouseClicked

    private void undergraduateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undergraduateLblMouseClicked
        
        unGup=new AdministratorUndergraduateUpdate();
        unGup.setVisible(true);
        unGup.setLocationRelativeTo(null);
    }//GEN-LAST:event_undergraduateLblMouseClicked

    private void calendarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarLblMouseClicked
        CalendarAdjustDateAndTime cal=new CalendarAdjustDateAndTime();
        cal.setVisible(true);
        cal.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_calendarLblMouseClicked

    private void registerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLblMouseClicked
        
        this.setVisible(false);
        ChooseStudentType chooseStudentType=new ChooseStudentType();
        chooseStudentType.setVisible(true);
        chooseStudentType.setLocationRelativeTo(null);
    }//GEN-LAST:event_registerLblMouseClicked

    private void instructorLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorLblMouseClicked
        
        adInUp=new AdministratorInstructorUpdate();
        adInUp.setVisible(true);
        adInUp.setLocationRelativeTo(null);

    }//GEN-LAST:event_instructorLblMouseClicked

    private void lecturerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerLblMouseClicked
        
        adLecUp=new AdministratorLecturerUpdate();
        adLecUp.setVisible(true);
        adLecUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_lecturerLblMouseClicked

    private void courseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseLblMouseClicked
        try {
            
            adCsUp=new AdministratorCourseUpdate();
            adCsUp.setVisible(true);
            adCsUp.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_courseLblMouseClicked

    private void examinationLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examinationLblMouseClicked
        
        exmUp=new AdministratorExamUpdate();
        exmUp.setVisible(true);
        exmUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_examinationLblMouseClicked

    private void locationsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationsLblMouseClicked
       
        adLoc=new AdministratotLocationUpdate();
        adLoc.setVisible(true);
        adLoc.setLocationRelativeTo(null);
    }//GEN-LAST:event_locationsLblMouseClicked

    private void subjectLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectLblMouseClicked
        
        subUp=new AdministratorSubjectsUpdate();
        subUp.setVisible(true);
        subUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_subjectLblMouseClicked

    private void teachingAllocationLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachingAllocationLblMouseClicked
        
        time=new AdministratorTimeAllocation();
        time.setVisible(true);
        time.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_teachingAllocationLblMouseClicked

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // Administrator close button
        this.dispose();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void assignmentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentLblMouseClicked
        adAsUp=new AdministratorAssignmentUpdate();
        adAsUp.setVisible(true);
        adAsUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_assignmentLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignmentLbl;
    private javax.swing.JLabel calendarLbl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel examinationLbl;
    private javax.swing.JLabel instructorLbl;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lecturerLbl;
    private javax.swing.JLabel locationsLbl;
    private javax.swing.JLabel postgraduateLbl;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JLabel teachingAllocationLbl;
    private javax.swing.JLabel undergraduateLbl;
    // End of variables declaration//GEN-END:variables
}
