/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.AssignmentGradeController.insertAssignmentGrades;
import static Controller.AssignmentGradeController.searchAssignmentGradeByTypeAndSubjectAndStudentID;
import static Controller.PostgraduateController.searchPostgraduateByYear;
import static Controller.SubjectController.searchSubjectBySemesterAndYearAndDepartmentIDAndType;
import static Controller.UndergraduateController.searchUndergraduateByYear;
import Model.AssignmentGrades;
import Model.Subject;
import static View.AdministratorExamUpdate.grade;
import static View.AdministratorExamUpdate.list;
import static View.AdministratorHome.asm;
import static View.AdministratorLogin.administratorHome;
import static View.EnrollementSystemHome.depid;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asitha
 */
public class AdministratorAssignmentUpdate extends javax.swing.JFrame {
    public static ArrayList<AssignmentGrades> as=new ArrayList<AssignmentGrades>();
    public static AssignmentGrades ass=new AssignmentGrades();
    
    
    /**
     * Creates new form AdministratorAssignmentUpdate
     */
    public AdministratorAssignmentUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        StudentTypeComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        semesterComboBox = new javax.swing.JComboBox<>();
        studentIDComboBox = new javax.swing.JComboBox<>();
        findStudentBtn = new javax.swing.JButton();
        SubjectIDComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AssignmentTypeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gradeComboBox = new javax.swing.JTextField();
        findResultsBtn = new javax.swing.JButton();
        addResultsBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        assignmentIDTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrator Assignment Result Managent Panel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        StudentTypeComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        StudentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Undergraduate", "Postgraduate" }));
        StudentTypeComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        yearComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        yearComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        semesterComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        semesterComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        studentIDComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        studentIDComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        findStudentBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        findStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.png"))); // NOI18N
        findStudentBtn.setText("Find Students");
        findStudentBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findStudentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        findStudentBtn.setPreferredSize(new java.awt.Dimension(250, 50));
        findStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentBtnActionPerformed(evt);
            }
        });

        SubjectIDComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        SubjectIDComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel3.setText("Subject ID");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel4.setText("Assignment Type");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 50));

        AssignmentTypeComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        AssignmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Class", "Practical", "Take Home", "Project", "Report" }));
        AssignmentTypeComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel5.setText("Result");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 50));

        resultTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        resultTxt.setPreferredSize(new java.awt.Dimension(550, 50));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel7.setText("Grade");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 50));

        gradeComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        gradeComboBox.setEnabled(false);
        gradeComboBox.setPreferredSize(new java.awt.Dimension(550, 50));

        findResultsBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        findResultsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.png"))); // NOI18N
        findResultsBtn.setText("Find Results");
        findResultsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findResultsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        findResultsBtn.setPreferredSize(new java.awt.Dimension(250, 50));
        findResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findResultsBtnActionPerformed(evt);
            }
        });

        addResultsBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        addResultsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus3.png"))); // NOI18N
        addResultsBtn.setText("Add Resuts");
        addResultsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addResultsBtn.setPreferredSize(new java.awt.Dimension(250, 50));
        addResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResultsBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel6.setText("Assignment ID");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel9.setText("Student ID");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel10.setText("Select Semester");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel11.setText("Select Year");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel12.setText("Select Student Type");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 50));

        assignmentIDTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        assignmentIDTxt.setPreferredSize(new java.awt.Dimension(550, 50));

        jLabel13.setBackground(new java.awt.Color(0, 153, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setOpaque(true);

        closeBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.setHideActionText(true);
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        closeBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        jLabel14.setText("Assignment Result Management Panel");
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(125, 125, 125)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semesterComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentIDComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubjectIDComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AssignmentTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gradeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(assignmentIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(findStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(findResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StudentTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StudentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(SubjectIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AssignmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(findResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Assignment Results", jPanel1);

        assm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject ID", "Assignment ID", "Assignment Type", "Result", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(assm);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1439, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Assignment Results", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResultsBtnActionPerformed
        
        String stud=(String)studentIDComboBox.getSelectedItem();
        String subject=(String)SubjectIDComboBox.getSelectedItem();
        String result=resultTxt.getText();
        gradeComboBox.setText((grade(result)));
        String grd=(String)gradeComboBox.getText();
        String semest=(String) semesterComboBox.getSelectedItem();
        String y=(String) yearComboBox.getSelectedItem();
        String aID=assignmentIDTxt.getText();
        String aTy=(String) AssignmentTypeComboBox.getSelectedItem();
        
        asm=new AssignmentGrades();
        asm.setAsgnmtnID(aID);
        asm.setStudentID(stud);
        asm.setSubjectID(subject);
        asm.setResult(result);
        asm.setGrade(grd);
        asm.setAssignmentType(aTy);

        try {
            if(insertAssignmentGrades(asm)>0){
                JOptionPane.showMessageDialog(rootPane, "Added successfully!!!");
                String subid=(String)SubjectIDComboBox.getSelectedItem();

                ArrayList<AssignmentGrades>l;
        
                l = searchAssignmentGradeByTypeAndSubjectAndStudentID((String)AssignmentTypeComboBox.getSelectedItem(), (String)SubjectIDComboBox.getSelectedItem(),(String)studentIDComboBox.getSelectedItem());
                DefaultTableModel dtm = (DefaultTableModel) assm.getModel();
                dtm.setRowCount(0);
                for (AssignmentGrades lo : l) {
                    Object[] rowData = {lo.getStudentID(),lo.getSubjectID(),lo.getAsgnmtnID(),lo.getAssignmentType(),lo.getResult(),lo.getGrade()};
                    dtm.addRow(rowData);
                }
        
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException n){
            JOptionPane.showMessageDialog(rootPane, "No Records Exists");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
    }//GEN-LAST:event_addResultsBtnActionPerformed

    private void findResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findResultsBtnActionPerformed
        
        String subid=(String)SubjectIDComboBox.getSelectedItem();

        ArrayList<AssignmentGrades>l;
        try {
            l = searchAssignmentGradeByTypeAndSubjectAndStudentID((String)AssignmentTypeComboBox.getSelectedItem(), (String)SubjectIDComboBox.getSelectedItem(),(String)studentIDComboBox.getSelectedItem());
            DefaultTableModel dtm = (DefaultTableModel) assm.getModel();
            dtm.setRowCount(0);
            for (AssignmentGrades lo : l) {
                Object[] rowData = {lo.getStudentID(),lo.getSubjectID(),lo.getAsgnmtnID(),lo.getAssignmentType(),lo.getResult(),lo.getGrade()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException n){
            JOptionPane.showMessageDialog(rootPane, "No Records Exists");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
    }//GEN-LAST:event_findResultsBtnActionPerformed

    private void findStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentBtnActionPerformed
        
        if(StudentTypeComboBox.getSelectedItem().equals("Undergraduate")){
            String yr=(String)yearComboBox.getSelectedItem();
            String sm=(String)semesterComboBox.getSelectedItem();
            try {
                list=searchUndergraduateByYear(yr);

                String[] slist=new String[list.size()];
                slist=list.toArray(slist);
                studentIDComboBox.setModel(new DefaultComboBoxModel<>(slist));
                ArrayList<Subject>sbb=searchSubjectBySemesterAndYearAndDepartmentIDAndType(yr,sm,depid,"U");

                String sblist[]=new String[sbb.size()];
                for(int i=0;i<sbb.size();i++){
                    sblist[i]=(String)sbb.get(i).getSubjectID();
                }
                SubjectIDComboBox.setModel(new DefaultComboBoxModel<>(sblist));

            } catch (SQLException ex) {
                Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NullPointerException n){
                JOptionPane.showMessageDialog(rootPane, "No record exists");
            }
        }
        else if(StudentTypeComboBox.getSelectedItem().equals("Postgraduate")){
            String yr=(String)yearComboBox.getSelectedItem();
            String sm=(String)semesterComboBox.getSelectedItem();
            try {
                list=searchPostgraduateByYear(yr);

                String[] slist=new String[list.size()];
                slist=list.toArray(slist);
                studentIDComboBox.setModel(new DefaultComboBoxModel<>(slist));

                ArrayList<Subject>sbb=searchSubjectBySemesterAndYearAndDepartmentIDAndType(yr,sm,depid,"P");

                String sblist[]=new String[sbb.size()];
                for(int i=0;i<sbb.size();i++){
                    sblist[i]=(String)sbb.get(i).getSubjectID();
                }
                SubjectIDComboBox.setModel(new DefaultComboBoxModel<>(sblist));

            } catch (SQLException ex) {
                Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdministratorExamUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NullPointerException n){
                JOptionPane.showMessageDialog(rootPane, "No record exists");
            }
        }
    }//GEN-LAST:event_findStudentBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        administratorHome.setVisible(true);
        administratorHome.setLocationRelativeTo(null);
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorAssignmentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorAssignmentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorAssignmentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorAssignmentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorAssignmentUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AssignmentTypeComboBox;
    private javax.swing.JComboBox<String> StudentTypeComboBox;
    private javax.swing.JComboBox<String> SubjectIDComboBox;
    private javax.swing.JButton addResultsBtn;
    private javax.swing.JTextField assignmentIDTxt;
    private javax.swing.JTable assm;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton findResultsBtn;
    private javax.swing.JButton findStudentBtn;
    private javax.swing.JTextField gradeComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField resultTxt;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JComboBox<String> studentIDComboBox;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
