/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.LecturerController.updateLecturer;
import static Controller.TimeController.searchTeachingAllocationByLecturerID;
import Model.Time;
import static View.EnrollementSystemHome.hm;
import static View.LecturerLogin.lec;
import static View.LecturerLogin.lecHome;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asitha
 */
public class LecturerHome extends javax.swing.JFrame {
    /**
     * Creates new form LecturerHome
     */
    public LecturerHome() {
        initComponents();
        this.loadPersonalDetails();
        this.loadTimeAllocations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        NICTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        editDetailsBtn = new javax.swing.JButton();
        updateDetailsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwd2 = new javax.swing.JTextField();
        changePasswordBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        personalDetailTopicLbl = new javax.swing.JLabel();
        changePasswordTopicLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        times = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lecturer Management Panel");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel4.setText("Name");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel5.setText("Phone");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel6.setText("National Identity Card");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel7.setText("Address");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 50));

        nameTxt.setEnabled(false);
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        phoneTxt.setEnabled(false);

        NICTxt.setEnabled(false);

        addressTxt.setEnabled(false);

        editDetailsBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        editDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editBtn.png"))); // NOI18N
        editDetailsBtn.setText("Edit Details");
        editDetailsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDetailsBtnActionPerformed(evt);
            }
        });

        updateDetailsBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        updateDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update1.png"))); // NOI18N
        updateDetailsBtn.setText("Update Details");
        updateDetailsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updateDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel1.setText("Type your new password");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        pwd1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        pwd1.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel2.setText("Re type your new password");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));

        pwd2.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        pwd2.setPreferredSize(new java.awt.Dimension(100, 50));

        changePasswordBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        changePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/changePasswordBtn1.png"))); // NOI18N
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        changePasswordBtn.setMaximumSize(new java.awt.Dimension(250, 50));
        changePasswordBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);

        personalDetailTopicLbl.setBackground(new java.awt.Color(255, 255, 255));
        personalDetailTopicLbl.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        personalDetailTopicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accountBtn1.png"))); // NOI18N
        personalDetailTopicLbl.setText("Personal Details");
        personalDetailTopicLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        personalDetailTopicLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        personalDetailTopicLbl.setOpaque(true);
        personalDetailTopicLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        changePasswordTopicLbl.setBackground(new java.awt.Color(255, 255, 255));
        changePasswordTopicLbl.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        changePasswordTopicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/passwordBtn1.png"))); // NOI18N
        changePasswordTopicLbl.setText("Change Password");
        changePasswordTopicLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        changePasswordTopicLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        changePasswordTopicLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        exitBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        exitBtn.setText("Close");
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitBtn.setMaximumSize(new java.awt.Dimension(250, 50));
        exitBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTxt)
                            .addComponent(NICTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(addressTxt))
                    .addComponent(personalDetailTopicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePasswordTopicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwd1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                            .addComponent(pwd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalDetailTopicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePasswordTopicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lecturer Details", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        times.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        times.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecturer ID", "Year", "Semester", "Subject ID", "Location ID", "Instructor ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(times);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Time Allocation", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void loadTimeAllocations(){
        try {
            String lecid=lec.getLecturerID();
            ArrayList<Time> l = searchTeachingAllocationByLecturerID(lecid);
             DefaultTableModel dtm = (DefaultTableModel) times.getModel();
            dtm.setRowCount(0);
            for (Time lo : l) {
                Object[] rowData = {lo.getLecID(),lo.getYr(),lo.getSem(),lo.getSubID(),lo.getLocID(),lo.getInsID()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorInstructorUpdate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorInstructorUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:
        if(pwd1.getText().equals(pwd2.getText())){
            lec.setLecturerPassword(pwd1.getText());

            try {
                if(updateLecturer(lec)>0){
                    JOptionPane.showMessageDialog(rootPane, "Passwrod updated!!!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Please try again later!!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LecturerHome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LecturerHome.class.getName()).log(Level.SEVERE, null, ex);
            }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Your passwords do not matched");
        }
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void updateDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsBtnActionPerformed
        
        String name=nameTxt.getText();
        String adrs=addressTxt.getText();
        String nic=NICTxt.getText();
        String phn=phoneTxt.getText();

        lec.setLecturerName(name);
        lec.setLecturerAddress(adrs);
        lec.setLecturerNIC(nic);
        lec.setLecturerPhone(phn);
        lec.setLecturerPassword(lec.getLecturerPassword());

        try {
            if(updateLecturer(lec)>0){
                JOptionPane.showMessageDialog(rootPane, "Update successfull!!!");
                this.setVisible(false);
                lecHome.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "There was a problem while updating");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LecturerHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LecturerHome.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }

    }//GEN-LAST:event_updateDetailsBtnActionPerformed

    private void editDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDetailsBtnActionPerformed
        nameTxt.setEnabled(true);
        phoneTxt.setEnabled(true);
        addressTxt.setEnabled(true);
        NICTxt.setEnabled(true);
    }//GEN-LAST:event_editDetailsBtnActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
         
    }//GEN-LAST:event_nameTxtActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
    }//GEN-LAST:event_exitBtnActionPerformed
    void loadPersonalDetails(){
        nameTxt.setText(lec.getLecturerName());
        NICTxt.setText(lec.getLecturerNIC());
        phoneTxt.setText(lec.getLecturerPhone());
        addressTxt.setText(lec.getLecturerAddress());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NICTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel changePasswordTopicLbl;
    private javax.swing.JButton editDetailsBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel personalDetailTopicLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField pwd1;
    private javax.swing.JTextField pwd2;
    private javax.swing.JTable times;
    private javax.swing.JButton updateDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
