/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.AssignmentGradeController.searchAssignmentGradeByStudentID;
import static Controller.ExamGradeController.searchExamGradeByStudentID;
import static Controller.PostgraduateController.updatePostgraduatePassword;
import static Controller.PostgraduateController.updatePostgraduatePersonal;
import Model.AssignmentGrades;
import Model.ExamGrades;
import static View.EnrollementSystemHome.hm;
import static View.PostgraduateLogin.pos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asitha
 */
public class PostgraduateHome extends javax.swing.JFrame {
    /**
     * Creates new form PostgraduateHome
     */
    public PostgraduateHome() {
        initComponents();
        this.loadPersonalDetails();
        this.loadAssignmentResults();
        this.loadExamResults();
    }
    void loadAssignmentResults(){
        try {
            ArrayList<AssignmentGrades>assignmentGradeses=searchAssignmentGradeByStudentID(pos.getId());
            if(assignmentGradeses.size()>0){
                DefaultTableModel dtm = (DefaultTableModel) assignmentResults.getModel();
                dtm.setRowCount(0);
                for(AssignmentGrades grades: assignmentGradeses){
                    Object[] rowData = {grades.getStudentID(),grades.getSubjectID(),grades.getAsgnmtnID(),grades.getAssignmentType(),grades.getResult(),grades.getGrade(),grades.getYear(),grades.getSemester()};
                    dtm.addRow(rowData);
                }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void loadExamResults(){
        try {
            ArrayList<ExamGrades>examGrade=searchExamGradeByStudentID(pos.getId());
            if(examGrade.size()>0){
                DefaultTableModel dtm = (DefaultTableModel) examResults.getModel();
                dtm.setRowCount(0);
                for(ExamGrades grades: examGrade){
                    Object[] rowData = {grades.getStudentID(),grades.getSubjectID(),grades.getResult(),grades.getGrade(),grades.getYear(),grades.getSemester()};
                    dtm.addRow(rowData);
                }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void loadPersonalDetails(){
        nameTxt.setText(pos.getName());
        telephoneTxt.setText(pos.getTelephone());
        addressTxt.setText(pos.getAddress());
        nicTxt.setText(pos.getNic());
        dobTxt.setText(pos.getDob());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        telephoneTxt = new javax.swing.JTextField();
        NICLbl = new javax.swing.JLabel();
        nicTxt = new javax.swing.JTextField();
        addressLbl = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        DOBLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        editDetailsBtn = new javax.swing.JButton();
        updateDetailBtn = new javax.swing.JButton();
        secPswd = new javax.swing.JTextField();
        changePasswordBtn = new javax.swing.JButton();
        password2Lbl = new javax.swing.JLabel();
        password1Lbl = new javax.swing.JLabel();
        frstPswd = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        personalDetailTopicLbl = new javax.swing.JLabel();
        changePasswordTopicLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignmentResults = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        examResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Postgraduate Management Panel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nameLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        nameLbl.setText("Name");
        nameLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        nameLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        nameLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        nameTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        nameTxt.setAlignmentX(2.0F);
        nameTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTxt.setEnabled(false);
        nameTxt.setPreferredSize(new java.awt.Dimension(50, 50));

        phoneLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        phoneLbl.setText("Phone");
        phoneLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        phoneLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        phoneLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        telephoneTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        telephoneTxt.setAlignmentX(2.0F);
        telephoneTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telephoneTxt.setEnabled(false);
        telephoneTxt.setPreferredSize(new java.awt.Dimension(50, 50));

        NICLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        NICLbl.setText("National Identity Card");
        NICLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        NICLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        NICLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        nicTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        nicTxt.setAlignmentX(2.0F);
        nicTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nicTxt.setEnabled(false);
        nicTxt.setPreferredSize(new java.awt.Dimension(50, 50));

        addressLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        addressLbl.setText("Address");
        addressLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        addressLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        addressLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        addressTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        addressTxt.setAlignmentX(2.0F);
        addressTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addressTxt.setEnabled(false);
        addressTxt.setPreferredSize(new java.awt.Dimension(50, 50));

        DOBLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        DOBLbl.setText("Date Of Birth");

        dobTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        dobTxt.setAlignmentX(2.0F);
        dobTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dobTxt.setEnabled(false);
        dobTxt.setPreferredSize(new java.awt.Dimension(50, 50));

        editDetailsBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        editDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editBtn.png"))); // NOI18N
        editDetailsBtn.setText("Edit Details");
        editDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editDetailsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDetailsBtnActionPerformed(evt);
            }
        });

        updateDetailBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        updateDetailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update1.png"))); // NOI18N
        updateDetailBtn.setText("Update Details");
        updateDetailBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateDetailBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updateDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailBtnActionPerformed(evt);
            }
        });

        secPswd.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        secPswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        secPswd.setPreferredSize(new java.awt.Dimension(50, 50));

        changePasswordBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        changePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/changePasswordBtn1.png"))); // NOI18N
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        changePasswordBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        changePasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordBtnMouseEntered(evt);
            }
        });
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });

        password2Lbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        password2Lbl.setText("Retype password");

        password1Lbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        password1Lbl.setText("Type your password");

        frstPswd.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        frstPswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        frstPswd.setPreferredSize(new java.awt.Dimension(50, 50));

        cancelBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        cancelBtn.setText("Close");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);

        personalDetailTopicLbl.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        personalDetailTopicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accountBtn1.png"))); // NOI18N
        personalDetailTopicLbl.setText("Personal Details");
        personalDetailTopicLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        personalDetailTopicLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        personalDetailTopicLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        changePasswordTopicLbl.setBackground(new java.awt.Color(51, 255, 255));
        changePasswordTopicLbl.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        changePasswordTopicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/passwordBtn1.png"))); // NOI18N
        changePasswordTopicLbl.setText("Change Password");
        changePasswordTopicLbl.setMaximumSize(new java.awt.Dimension(100, 50));
        changePasswordTopicLbl.setMinimumSize(new java.awt.Dimension(100, 50));
        changePasswordTopicLbl.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personalDetailTopicLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NICLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBLbl))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telephoneTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nicTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateDetailBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(editDetailsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(frstPswd, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                                    .addComponent(secPswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(changePasswordTopicLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(changePasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalDetailTopicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NICLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateDetailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(changePasswordTopicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frstPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secPswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Postgraduate Details", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        assignmentResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject ID", "Assignment ID", "Assignment Type", "Result", "Grade", "Year", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(assignmentResults);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Assignment Results", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        examResults.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        examResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject ID", "Result", "Grade", "Year", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(examResults);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exam Results", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        // TODO add your handling code here:

        if(frstPswd.getText().equals(secPswd.getText())){
            try {
                pos.setPassword(frstPswd.getText());
            
                if(updatePostgraduatePassword(pos)>0){
                    JOptionPane.showMessageDialog(rootPane, "Password updated succesfully!!!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
            }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Passwords does not match");
        }
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void changePasswordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordBtnMouseEntered

    private void updateDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailBtnActionPerformed
        
        try {
            pos.setName(nameTxt.getText());
            pos.setAddress(addressTxt.getText());
            pos.setDob(dobTxt.getText());
            pos.setNic(nicTxt.getText());
            pos.setTelephone(telephoneTxt.getText());
            
            
            if(updatePostgraduatePersonal(pos)>0){
                JOptionPane.showMessageDialog(rootPane, "Update success!!!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Try again later");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateHome.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
       
    }//GEN-LAST:event_updateDetailBtnActionPerformed

    private void editDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDetailsBtnActionPerformed
        nameTxt.setEnabled(true);
        addressTxt.setEnabled(true);
        nicTxt.setEnabled(true);
        dobTxt.setEnabled(true);
        telephoneTxt.setEnabled(true);
    }//GEN-LAST:event_editDetailsBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBLbl;
    private javax.swing.JLabel NICLbl;
    private javax.swing.JLabel addressLbl;
    private static javax.swing.JTextField addressTxt;
    private javax.swing.JTable assignmentResults;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel changePasswordTopicLbl;
    private static javax.swing.JTextField dobTxt;
    private javax.swing.JButton editDetailsBtn;
    private javax.swing.JTable examResults;
    private javax.swing.JTextField frstPswd;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLbl;
    private static javax.swing.JTextField nameTxt;
    private static javax.swing.JTextField nicTxt;
    private javax.swing.JLabel password1Lbl;
    private javax.swing.JLabel password2Lbl;
    private javax.swing.JLabel personalDetailTopicLbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField secPswd;
    private static javax.swing.JTextField telephoneTxt;
    private javax.swing.JButton updateDetailBtn;
    // End of variables declaration//GEN-END:variables
}
