/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.CourseController.searchCourseByCourseName;
import static Controller.CourseController.searchCourseByDepartmentIDandDegreeID;
import static Controller.PostgraduateController.deletePostgraduate;
import static Controller.StudentSubjectController.deleteStudentSubject;
import static Controller.StudentSubjectController.insertStudentSubject;
import static Controller.SubjectController.search4SubjectsByCourseIDAndYearAndSemester;
import static Controller.SubjectController.searchOther4SubjectsByCourseIDAndYearAndSemester;
import Model.StudentSubject;
import Model.Subject;
import static View.PostgraduateLogin.pos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Course;
import Model.Mailer;
import static Model.Season.eligibleFebruarySeason;
import static Model.Season.eligibleJulySeason;
import static View.EnrollementSystemHome.depid;
import static View.EnrollementSystemHome.hm;

/**
 *
 * @author Asitha
 */
public class PostgraduateCourseRegister extends javax.swing.JFrame {
    private static ArrayList<Subject>coreSub=new ArrayList<>();
    private static ArrayList<Subject>otherSub=new ArrayList<>();
    private static ArrayList<Integer>cost=new ArrayList<>();
    private static int count=0;
    private DefaultTableModel dtm;
        
    /**
     * Creates new form PostgraduateCourseRegister
     */
    public PostgraduateCourseRegister() {
        dtm=new DefaultTableModel();
        initComponents();
        this.loadCourse();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        selectYearLbl = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        selectSemesterLbl = new javax.swing.JLabel();
        selectCourseLbl = new javax.swing.JLabel();
        CourseComboBox = new javax.swing.JComboBox<>();
        semesterComboBox = new javax.swing.JComboBox<>();
        otherSub1ComboBox = new javax.swing.JComboBox<>();
        selectFOptionalLbl = new javax.swing.JLabel();
        selectSOptionalSubject = new javax.swing.JLabel();
        selectTOptionalSubject = new javax.swing.JLabel();
        otherSub2ComboBox = new javax.swing.JComboBox<>();
        otherSub3ComboBox = new javax.swing.JComboBox<>();
        proceedBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        addOptionalSubjectsBtn = new javax.swing.JButton();
        selectYearLbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subTables = new javax.swing.JTable();
        totalPaymentLblName = new javax.swing.JLabel();
        totalPaymentLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Postgraduate Course Register");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        selectYearLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectYearLbl.setText("Select Year");

        yearComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        selectSemesterLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectSemesterLbl.setText("Select Semester");

        selectCourseLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectCourseLbl.setText("Select Course");

        CourseComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        CourseComboBox.setPreferredSize(new java.awt.Dimension(50, 50));
        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });

        semesterComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        otherSub1ComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        otherSub1ComboBox.setPreferredSize(new java.awt.Dimension(50, 50));
        otherSub1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSub1ComboBoxActionPerformed(evt);
            }
        });

        selectFOptionalLbl.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectFOptionalLbl.setText("Select first subject");
        selectFOptionalLbl.setPreferredSize(new java.awt.Dimension(50, 50));

        selectSOptionalSubject.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectSOptionalSubject.setText("Select second subject");
        selectSOptionalSubject.setPreferredSize(new java.awt.Dimension(50, 50));

        selectTOptionalSubject.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectTOptionalSubject.setText("Select third subject");
        selectTOptionalSubject.setPreferredSize(new java.awt.Dimension(50, 50));

        otherSub2ComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        otherSub2ComboBox.setPreferredSize(new java.awt.Dimension(50, 50));
        otherSub2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSub2ComboBoxActionPerformed(evt);
            }
        });

        otherSub3ComboBox.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        otherSub3ComboBox.setPreferredSize(new java.awt.Dimension(50, 50));
        otherSub3ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSub3ComboBoxActionPerformed(evt);
            }
        });

        proceedBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        proceedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next2.png"))); // NOI18N
        proceedBtn.setText("Next");
        proceedBtn.setHideActionText(true);
        proceedBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        proceedBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        proceedBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Ubuntu", 1, 19)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        cancelBtn.setText("Close");
        cancelBtn.setHideActionText(true);
        cancelBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cancelBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);

        addOptionalSubjectsBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addOptionalSubjectsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus3.png"))); // NOI18N
        addOptionalSubjectsBtn.setText("Add Subjects");
        addOptionalSubjectsBtn.setHideActionText(true);
        addOptionalSubjectsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addOptionalSubjectsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addOptionalSubjectsBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        addOptionalSubjectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOptionalSubjectsBtnActionPerformed(evt);
            }
        });

        selectYearLbl1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectYearLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        selectYearLbl1.setText("Postgraduate Course Selection Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectYearLbl1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectCourseLbl)
                            .addComponent(selectYearLbl)
                            .addComponent(selectSemesterLbl)
                            .addComponent(selectFOptionalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectSOptionalSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectTOptionalSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CourseComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(semesterComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otherSub1ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otherSub2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otherSub3ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(proceedBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addOptionalSubjectsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(selectYearLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectYearLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(semesterComboBox)
                    .addComponent(selectSemesterLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCourseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(otherSub1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherSub2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherSub3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectFOptionalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectSOptionalSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectTOptionalSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOptionalSubjectsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Postgraduate Course Register", jPanel1);

        subTables.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        subTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name", "Semester", "Year", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(subTables);

        totalPaymentLblName.setText("Total Payment");

        totalPaymentLbl.setBackground(new java.awt.Color(255, 0, 0));
        totalPaymentLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalPaymentLbl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalPaymentLblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPaymentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalPaymentLblName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPaymentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Selected  Subjects", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Get main 4 subjects
     */
    public static ArrayList<Subject> getCoreSub() {
        return coreSub;
    }

    /**
     * Set Main 4 subjects
     */
    public static void setCoreSub(ArrayList<Subject> aCoreSub) {
        coreSub = aCoreSub;
    }

    /**
     * Get optional subjects
     */
    public static ArrayList<Subject> getOtherSub() {
        return otherSub;
    }

    /**
     * Set optional subjects
     */
    public static void setOtherSub(ArrayList<Subject> aOtherSub) {
        otherSub = aOtherSub;
    }

    /**
     * Get how many times does data collected
     */
    public static int getCount() {
        return count;
    }

    /**
     * Set count of data have been collected about subjects
     */
    public static void setCount(int aCount) {
        count = aCount;
    }
    
    public javax.swing.JComboBox<String> getSelectCourse() {
        return CourseComboBox;
    }

    public void setSelectCourse(javax.swing.JComboBox<String> selectCourse) {
        this.CourseComboBox = selectCourse;
    }

    

    public javax.swing.JComboBox<String> getOtherSub1() {
        return otherSub1ComboBox;
    }

    public void setOtherSub1(javax.swing.JComboBox<String> otherSub1) {
        this.otherSub1ComboBox = otherSub1;
    }

    public javax.swing.JComboBox<String> getOtherSub2() {
        return otherSub2ComboBox;
    }

    public void setOtherSub2(javax.swing.JComboBox<String> otherSub2) {
        this.otherSub2ComboBox = otherSub2;
    }

    public javax.swing.JComboBox<String> getOtherSub3() {
        return otherSub3ComboBox;
    }

    public void setOtherSub3(javax.swing.JComboBox<String> otherSub3) {
        this.otherSub3ComboBox = otherSub3;
    }

    
    public javax.swing.JComboBox<String> getSelectSemester() {
        return semesterComboBox;
    }

    public void setSelectSemester(javax.swing.JComboBox<String> selectSemester) {
        this.semesterComboBox = selectSemester;
    }

    public javax.swing.JComboBox<String> getSelectYear() {
        return yearComboBox;
    }

    public void setSelectYear(javax.swing.JComboBox<String> selectYear) {
        this.yearComboBox = selectYear;
    }

    
    public void loadCourse(){
        try {
            ArrayList<Course>courses=searchCourseByDepartmentIDandDegreeID(depid,"P");//Search all postgraduate courses with respect to department
            if(courses.size()>0){
                ArrayList<String>courseNames=new ArrayList<>();
                
                for(Course cs: courses){
                    courseNames.add(cs.getName());
                }
                
                String courseNamesStringArray[]= new String[courses.size()];
                courseNamesStringArray= courseNames.toArray(courseNamesStringArray);
                
                CourseComboBox.setModel(new DefaultComboBoxModel<>(courseNamesStringArray));
                
                if(eligibleJulySeason()){//If registration eligible for july it sets semester 2 by default
                    semesterComboBox.setSelectedIndex(1);
                    semesterComboBox.setEditable(false);
                    semesterComboBox.setEnabled(false);
                }
               
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"There are no courses avaiable for you.");
                this.setVisible(false);
                hm.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            System.out.println(e.toString());
        }
    }
    
    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        try {
        String yr=(String)getSelectYear().getSelectedItem();
        String sem=(String)getSelectSemester().getSelectedItem();
        String cs=(String)getSelectCourse().getSelectedItem();
        String deg=searchCourseByCourseName(cs);

        setCoreSub(search4SubjectsByCourseIDAndYearAndSemester(deg,yr,sem));

            if(coreSub.size()>0){
                dtm=(DefaultTableModel) subTables.getModel();
                dtm.setRowCount(0);

                for (Subject sub : getCoreSub()) {
                    Object[] rowData = {sub.getSubjectID(), sub.getSubjectName(),sub.getSubjectSemester(),sub.getSubjectYear(),sub.getPrice()};
                    dtm.addRow(rowData);
                }
                
                //Set optional subject in combo boxes
                setOtherSub(searchOther4SubjectsByCourseIDAndYearAndSemester(deg,yr,sem));
                String otherSubName[]=new String[4];

                for(int i=0;i<otherSub.size();i++){
                    otherSubName[i]=(String)(getOtherSub().get(i).getSubjectName());
                }

                getOtherSub1().setModel(new DefaultComboBoxModel<>(otherSubName));
                getOtherSub2().setModel(new DefaultComboBoxModel<>(otherSubName));
                getOtherSub3().setModel(new DefaultComboBoxModel<>(otherSubName));

            }
            else{
                JOptionPane.showMessageDialog(rootPane, "There are no subjects available for your course.");
            }
    } catch (SQLException ex) {
        Logger.getLogger(UndergraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(UndergraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    private void otherSub1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSub1ComboBoxActionPerformed
        // Check whether same subjects have choosen.
        if((getOtherSub2().getSelectedIndex()==getOtherSub1().getSelectedIndex())||(getOtherSub3().getSelectedIndex()==getOtherSub1().getSelectedIndex())){
            JOptionPane.showMessageDialog(rootPane, "InvalidSelection: Select 3 different courses");
        }
        
       
    }//GEN-LAST:event_otherSub1ComboBoxActionPerformed

    private void otherSub2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSub2ComboBoxActionPerformed
        // Check whether same subjects have choosen.
        if((getOtherSub1().getSelectedIndex()==getOtherSub2().getSelectedIndex())||(getOtherSub3().getSelectedIndex()==getOtherSub2().getSelectedIndex())){
            JOptionPane.showMessageDialog(rootPane, "InvalidSelection: Select 3 different courses");
        }
    }//GEN-LAST:event_otherSub2ComboBoxActionPerformed

    private void otherSub3ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSub3ComboBoxActionPerformed
        // Check whether same subjects have choosen.
        if((getOtherSub2().getSelectedIndex()==getOtherSub3().getSelectedIndex())||(getOtherSub1().getSelectedIndex()==getOtherSub3().getSelectedIndex())){
            JOptionPane.showMessageDialog(rootPane, "InvalidSelection: Select 3 different courses");
        }
    }//GEN-LAST:event_otherSub3ComboBoxActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        // Insert user's subject details according to season
        try{
            
        if(eligibleJulySeason()){
            
            //Insert core subject details in to database
            for(int i=0;i<4;i++){
                
                StudentSubject studentSubject=new StudentSubject();
                
                studentSubject.setStudentID(pos.getId());
                studentSubject.setSubjectID(getCoreSub().get(i).getSubjectID());
                
                insertStudentSubject(studentSubject);
               
                }
            
            //Insert optional subject details to database
            int sub1=getOtherSub1().getSelectedIndex();
            int sub2=getOtherSub2().getSelectedIndex();
            int sub3=getOtherSub3().getSelectedIndex();

            StudentSubject studentSubject=new StudentSubject();
            
            //Insert first optional subject
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub1).getSubjectID());
            insertStudentSubject(studentSubject);
            
            //Insert 2 optional subject
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub2).getSubjectID());
            insertStudentSubject(studentSubject);
            
            //Insert 3 optional subject
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub3).getSubjectID());
            insertStudentSubject(studentSubject);
            
            //Open a login form for the user
            this.setVisible(false);
            PostgraduateLogin postgraduateLogin=new PostgraduateLogin();
            postgraduateLogin.setVisible(true);
            postgraduateLogin.setLocationRelativeTo(null);
            

        }
        else if(eligibleFebruarySeason()){
            
            if(getCount()>1){
                for(int i=0;i<4;i++){
                StudentSubject studentSubject=new StudentSubject();
                studentSubject.setStudentID(pos.getId());
                studentSubject.setSubjectID(getCoreSub().get(i).getSubjectID());
                
                insertStudentSubject(studentSubject);
                }
                
                
            int sub1=getOtherSub1().getSelectedIndex();
            int sub2=getOtherSub2().getSelectedIndex();
            int sub3=getOtherSub3().getSelectedIndex();

            StudentSubject studentSubject=new StudentSubject();
            
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub1).getSubjectID());
            insertStudentSubject(studentSubject);
            
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub2).getSubjectID());
            insertStudentSubject(studentSubject);
            
            studentSubject.setStudentID(pos.getId());
            studentSubject.setSubjectID(getOtherSub().get(sub3).getSubjectID());
            insertStudentSubject(studentSubject);
            
            JOptionPane.showMessageDialog(rootPane, "Please select subjects for your 2nd semester");
            
            getSelectSemester().setSelectedIndex(2);
            getSelectYear().setSelectedIndex(getSelectYear().getSelectedIndex());
            getSelectCourse().setSelectedIndex(getSelectCourse().getSelectedIndex());

            getSelectCourse().setEditable(false);
            getSelectCourse().setEnabled(false);
            getSelectSemester().setEditable(false);
            getSelectSemester().setEnabled(false);
            getSelectYear().setEditable(false);
            getSelectYear().setEnabled(false);
            }
            
            else{
                for(int i=0;i<4;i++){
                    StudentSubject studentSubject=new StudentSubject();
                    studentSubject.setStudentID(pos.getId());
                    studentSubject.setSubjectID(getCoreSub().get(i).getSubjectID());

                    insertStudentSubject(studentSubject);
                }
                
                int sub1=getOtherSub1().getSelectedIndex();
                int sub2=getOtherSub2().getSelectedIndex();
                int sub3=getOtherSub3().getSelectedIndex();

                StudentSubject studentSubject=new StudentSubject();

                studentSubject.setStudentID(pos.getId());
                studentSubject.setSubjectID(getOtherSub().get(sub1).getSubjectID());
                insertStudentSubject(studentSubject);

                studentSubject.setStudentID(pos.getId());
                studentSubject.setSubjectID(getOtherSub().get(sub2).getSubjectID());
                insertStudentSubject(studentSubject);

                studentSubject.setStudentID(pos.getId());
                studentSubject.setSubjectID(getOtherSub().get(sub3).getSubjectID());
                insertStudentSubject(studentSubject);
                
                this.setVisible(false);
                PostgraduateLogin postgraduateLogin=new PostgraduateLogin();
                postgraduateLogin.setVisible(true);
                postgraduateLogin.setLocationRelativeTo(null);
            
            }
        }
        }catch (SQLException ex) {
                Logger.getLogger(UndergraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UndergraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        try {
            JOptionPane.showMessageDialog(rootPane, "Registration Canceled");
                    
            deletePostgraduate(pos);
            deleteStudentSubject(pos.getId());
            this.dispose();
            
            hm.setVisible(true);
            hm.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addOptionalSubjectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOptionalSubjectsBtnActionPerformed
        // Add subjects in comboxes to the subject table
        Object[] rowData = {getOtherSub().get(otherSub1ComboBox.getSelectedIndex()).getSubjectID(),getOtherSub().get(otherSub1ComboBox.getSelectedIndex()).getSubjectName(),getOtherSub().get(otherSub1ComboBox.getSelectedIndex()).getSubjectSemester(),getOtherSub().get(otherSub1ComboBox.getSelectedIndex()).getSubjectYear(),getOtherSub().get(otherSub1ComboBox.getSelectedIndex()).getPrice()};
        dtm.addRow(rowData);
        Object[] rowData2 = {getOtherSub().get(otherSub2ComboBox.getSelectedIndex()).getSubjectID(),getOtherSub().get(otherSub2ComboBox.getSelectedIndex()).getSubjectName(),getOtherSub().get(otherSub2ComboBox.getSelectedIndex()).getSubjectSemester(),getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getSubjectYear(),getOtherSub().get(otherSub2ComboBox.getSelectedIndex()).getPrice()};
        dtm.addRow(rowData2);
        Object[] rowData3 = {getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getSubjectID(),getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getSubjectName(),getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getSubjectSemester(),getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getSubjectYear(),getOtherSub().get(otherSub3ComboBox.getSelectedIndex()).getPrice()};
        dtm.addRow(rowData3);
        
        //Calculate toyal payment
        double totalPayment=0;
        System.out.println(subTables.getRowCount()+","+subTables.getValueAt(0, 4));
        for(int i=0;i<subTables.getRowCount();i++){
            totalPayment+=Double.parseDouble(subTables.getValueAt(i, 4).toString());
        }
        
        //Set total payment
        totalPaymentLbl.setText(Double.toString(totalPayment));
        
        //Get registering season
        String season=eligibleJulySeason()?"July":"February";
        
        //Generate invoice
        String invoice="Full Name: \t"+pos.getName()+"\nSeason: \t"+season+"\nSubject Details: \n\t"+
                       subTables.getValueAt(0, 1)+"\t"+subTables.getValueAt(0, 4)+
                "\n\t"+subTables.getValueAt(1, 1)+"\t"+subTables.getValueAt(1, 4)+
                "\n\t"+subTables.getValueAt(2, 1)+"\t"+subTables.getValueAt(2, 4)+
                "\n\t"+subTables.getValueAt(3, 1)+"\t"+subTables.getValueAt(3, 4)+
                "\n\t"+subTables.getValueAt(4, 1)+"\t"+subTables.getValueAt(4, 4)+
                "\n\t"+subTables.getValueAt(5, 1)+"\t"+subTables.getValueAt(5, 4)+
                "\n\t"+subTables.getValueAt(6, 1)+"\t"+subTables.getValueAt(6, 4)+
                "\nTotal payment: \t"+totalPayment;
        
        //Email invoice to user 
       try{
           Mailer.send("asithaindrajithk9@gmail.com","1995_asitha",pos.getEmail(),"Invoice ID: "+pos.getId(),invoice);
       }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Invalid Email address");
       }
    }//GEN-LAST:event_addOptionalSubjectsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateCourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateCourseRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CourseComboBox;
    private javax.swing.JButton addOptionalSubjectsBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> otherSub1ComboBox;
    private javax.swing.JComboBox<String> otherSub2ComboBox;
    private javax.swing.JComboBox<String> otherSub3ComboBox;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JLabel selectCourseLbl;
    private javax.swing.JLabel selectFOptionalLbl;
    private javax.swing.JLabel selectSOptionalSubject;
    private javax.swing.JLabel selectSemesterLbl;
    private javax.swing.JLabel selectTOptionalSubject;
    private javax.swing.JLabel selectYearLbl;
    private javax.swing.JLabel selectYearLbl1;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JTable subTables;
    private javax.swing.JLabel totalPaymentLbl;
    private javax.swing.JLabel totalPaymentLblName;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables

    
}
