/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.DepartmentController.searchDepartmentByDepartmentName;
import static Controller.PostgraduateController.deletePostgraduate;
import static Controller.PostgraduateController.insertPostgraduate;
import static Controller.PostgraduateController.searchPostgraduateByNIC;
import Model.Postgraduate;
import static Model.Season.eligibleFebruarySeason;
import static Model.Season.eligibleJulySeason;
import Model.Subject;
import static View.EnrollementSystemHome.depid;
import static View.EnrollementSystemHome.hm;
import static View.PostgraduateLogin.pos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asitha
 */
public class PostgraduateRegister extends javax.swing.JFrame {
    public static PostgraduateCourseRegister postgraduateCourseRegister;
    private static ArrayList<Subject>coreSub=new ArrayList<>();
    private static ArrayList<Subject>otherSub=new ArrayList<>();
    private static ArrayList<Integer>cost=new ArrayList<>();
    private static int count=0;

    
    /**
     * Creates new form PostgraduateRegister
     */
    public PostgraduateRegister() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        secQ = new javax.swing.JComboBox<>();
        nameTxt = new javax.swing.JTextField();
        NICTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        telephoneTxt = new javax.swing.JTextField();
        answerTxt = new javax.swing.JTextField();
        institute = new javax.swing.JComboBox<>();
        eduCol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateChooserBtn = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Postgraduate Personal Details Register");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel3.setText("National Identity Card Number");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel5.setText("Date Of Birth");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel6.setText("Address");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel4.setText("Telephone");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel1.setText("Education Qualifications");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel7.setText("Institute");

        secQ.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        secQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is you mother's maiden name?", "What is your teacher's name?", "What is your street name?", "What is your best friend's name?", "What is your father's surname?" }));

        nameTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        NICTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        addressTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        telephoneTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        answerTxt.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        institute.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        institute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "University Of Colombo School Of Computing", "ESOFT Metro Campus", "NSBM", "PCJT" }));

        eduCol.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close5.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(250, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next2.png"))); // NOI18N
        submit.setText("Next");
        submit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        submit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        submit.setMaximumSize(new java.awt.Dimension(250, 50));
        submit.setMinimumSize(new java.awt.Dimension(250, 50));
        submit.setPreferredSize(new java.awt.Dimension(250, 50));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);

        department.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School Of Computing", "School Of Engineering", "School Of Business" }));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel8.setText("Select Department");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings.png"))); // NOI18N
        jLabel9.setText("Postgraduate Personal Details Register");

        dateChooserBtn.setToolTipText("ex: 08-Aug-2018");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NICTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooserBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(secQ, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telephoneTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eduCol, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(institute, javax.swing.GroupLayout.Alignment.TRAILING, 0, 450, Short.MAX_VALUE)
                            .addComponent(answerTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eduCol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(answerTxt)
                    .addComponent(secQ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static ArrayList<Subject> getCoreSub() {
        return coreSub;
    }

    public static void setCoreSub(ArrayList<Subject> aCoreSub) {
        coreSub = aCoreSub;
    }

    public static ArrayList<Subject> getOtherSub() {
        return otherSub;
    }

    public static void setOtherSub(ArrayList<Subject> aOtherSub) {
        otherSub = aOtherSub;
    }

    public static ArrayList<Integer> getCost() {
        return cost;
    }

    public static void setCost(ArrayList<Integer> aCost) {
        cost = aCost;
    }


    public static int getCount() {
        return count;
    }
    
    

    public static void setCount(int aCount) {
        count = aCount;
    }
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {                                       
            // Get all values to strings
            String name=getNameTxt().getText();
            String nic=getNICTxt().getText();
            String dob=1900+dateChooserBtn.getDate().getYear()+"-"+(dateChooserBtn.getDate().getMonth()+1)+"-"+dateChooserBtn.getDate().getDate();
            String address=getAddressTxt().getText();
            String telephone=telephoneTxt.getText();
            String edu=(String)getEduCol().getSelectedItem();
            String institut=(String)institute.getSelectedItem();
            
            depid=searchDepartmentByDepartmentName((String)department.getSelectedItem()).getDepartmentID();
            
            String sequrity=(String)secQ.getSelectedItem();
            String answer=(String)getAnswerTxt().getText();
            
            //Create new Postgraduate Student and store all values
            pos=new Postgraduate();
            pos.setName(name);
            pos.setNic(nic);
            pos.setDob(dob);
            pos.setAddress(address);
            pos.setTelephone(telephone);
            pos.setInstitute(institut);
            pos.setQualifications(edu);
            pos.setDepartment(depid);
            pos.setSecurity(sequrity);
            pos.setAnswer(answer);
            
            if(insertPostgraduate(pos)>0){
                JOptionPane.showMessageDialog(rootPane, "You have succefully registered!!!");
                pos.setId(searchPostgraduateByNIC(pos.getNic()));
                JOptionPane.showMessageDialog(rootPane, "Your ID: "+pos.getId()+"\nYour password: NIC number");
                
                if(eligibleFebruarySeason()||eligibleJulySeason()){
                    this.setVisible(false);
                    postgraduateCourseRegister=new PostgraduateCourseRegister();
                    postgraduateCourseRegister.setVisible(true);
                    postgraduateCourseRegister.setLocationRelativeTo(null);
                }


                else{
                    System.out.println("hello");
                    JOptionPane.showMessageDialog(rootPane, "You can register only in january and july seasons only");
                    JOptionPane.showMessageDialog(rootPane, "Your records have deleted");
                    deletePostgraduate(pos);//delete postgraduate object
                    hm.setVisible(true);
                    hm.setLocationRelativeTo(null);

                }

            }
           
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateRegister.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Try again later!!!");
        }
       
    
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            deletePostgraduate(pos);//delete postgraduate object
            this.dispose();
            hm.setVisible(true);
            hm.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NICTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField answerTxt;
    private com.toedter.calendar.JDateChooser dateChooserBtn;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JComboBox<String> eduCol;
    private javax.swing.JComboBox<String> institute;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> secQ;
    private javax.swing.JButton submit;
    private javax.swing.JTextField telephoneTxt;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getEduCol() {
        return eduCol;
    }

    public void setEduCol(javax.swing.JComboBox<String> eduCol) {
        this.eduCol = eduCol;
    }

    public javax.swing.JTextField getNICTxt() {
        return NICTxt;
    }

    public void setNICTxt(javax.swing.JTextField NICTxt) {
        this.NICTxt = NICTxt;
    }

    public javax.swing.JTextField getAddressTxt() {
        return addressTxt;
    }

    public void setAddressTxt(javax.swing.JTextField addressTxt) {
        this.addressTxt = addressTxt;
    }

    public javax.swing.JTextField getAnswerTxt() {
        return answerTxt;
    }

    public void setAnswerTxt(javax.swing.JTextField answerTxt) {
        this.answerTxt = answerTxt;
    }

    public javax.swing.JTextField getNameTxt() {
        return nameTxt;
    }

    public void setNameTxt(javax.swing.JTextField nameTxt) {
        this.nameTxt = nameTxt;
    }
}
