/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.DepartmentController.searchDepartment;
import static Controller.LecturerController.searchLecturerID;
import Model.AssignmentGrades;
import Model.Course;
import Model.Department;
import Model.ExamGrades;
import Model.Instructor;
import Model.Lecturer;
import Model.Postgraduate;
import Model.Subject;
import Model.Undergraduate;
import static View.Home.hm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Asitha
 */
public class AdministratorHome extends javax.swing.JFrame {
    public static Undergraduate unG;
    public static Postgraduate posG;
    public static Subject sub;
    public static Course CS;
    public static Instructor ins;
    public static Lecturer lec;
    public static ExamGrades exm;
    public static AssignmentGrades asm;
    public static AdministratorUndergraduateUpdate unGup;
    public static AdministratorPostgraduateUpdate posGup;
    public static AdministratorSubjectsUpdate subUp;
    public static AdministratorExamUpdate exmUp;
    public static AdministratorTimeAllocation time;
    public static AdministratotLocationUpdate adLoc;
    public static AdministratorAssignmentUpdate adAsUp;
    public static AdministratorCourseUpdate adCsUp;
    public static AdministratorLecturerUpdate adLecUp;
    public static AdministratorInstructorUpdate adInUp;
    
    public static ArrayList<Lecturer> lc=new ArrayList<>();
    /**
     * Creates new form AdministratotProfile
     */
    public AdministratorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pH = new javax.swing.JButton();
        insH = new javax.swing.JButton();
        lecH = new javax.swing.JButton();
        tA = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        asmnt = new javax.swing.JButton();
        uH = new javax.swing.JButton();
        subBtn1 = new javax.swing.JButton();
        subBtn2 = new javax.swing.JButton();
        subBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-password-protection.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pH.setBackground(new java.awt.Color(255, 255, 255));
        pH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/post.png"))); // NOI18N
        pH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pHActionPerformed(evt);
            }
        });

        insH.setBackground(new java.awt.Color(255, 255, 255));
        insH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/instruc.png"))); // NOI18N
        insH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insHActionPerformed(evt);
            }
        });

        lecH.setBackground(new java.awt.Color(255, 255, 255));
        lecH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lec.png"))); // NOI18N
        lecH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecHActionPerformed(evt);
            }
        });

        tA.setBackground(new java.awt.Color(255, 255, 255));
        tA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/time_table.jpg"))); // NOI18N
        tA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAActionPerformed(evt);
            }
        });

        subBtn.setBackground(new java.awt.Color(255, 255, 255));
        subBtn.setText("examupdate");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        asmnt.setBackground(new java.awt.Color(255, 255, 255));
        asmnt.setText("asignmnt");
        asmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asmntActionPerformed(evt);
            }
        });

        uH.setBackground(new java.awt.Color(255, 255, 255));
        uH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/under_small.png"))); // NOI18N
        uH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uHActionPerformed(evt);
            }
        });

        subBtn1.setBackground(new java.awt.Color(255, 255, 255));
        subBtn1.setText("sub");
        subBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtn1ActionPerformed(evt);
            }
        });

        subBtn2.setBackground(new java.awt.Color(255, 255, 255));
        subBtn2.setText("course");
        subBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtn2ActionPerformed(evt);
            }
        });

        subBtn3.setBackground(new java.awt.Color(255, 255, 255));
        subBtn3.setText("Location");
        subBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insH, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lecH, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pH, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tA, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uH, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asmnt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tA, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uHActionPerformed
        // TODO add your handling code here:
        unGup=new AdministratorUndergraduateUpdate();
        unGup.setVisible(true);
        unGup.setLocationRelativeTo(null);
    }//GEN-LAST:event_uHActionPerformed

    private void pHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pHActionPerformed
        // TODO add your handling code here:
        posGup=new AdministratorPostgraduateUpdate();
        posGup.setVisible(true);
        posGup.setLocationRelativeTo(null);
    }//GEN-LAST:event_pHActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        exmUp=new AdministratorExamUpdate();
        exmUp.setVisible(true);
        exmUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_subBtnActionPerformed

    private void tAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAActionPerformed
        // TODO add your handling code here:
        time=new AdministratorTimeAllocation();
        time.setVisible(true);
        time.setLocationRelativeTo(null);
        try {
            ArrayList<String>l=new ArrayList<>();
            Department dep=new Department();
            dep=searchDepartment((String)hm.getSelectDepartment().getSelectedItem());
            lc=searchLecturerID(dep.getDepartmentID());
            for(Lecturer a:lc){
                l.add(a.getLecturerID());
            }
            String[] slist=new String[l.size()];
            slist=l.toArray(slist);
            time.getLec().setModel(new DefaultComboBoxModel<>(slist));
        } catch (SQLException ex) {
            Logger.getLogger(AdministratorHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdministratorHome.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_tAActionPerformed

    private void asmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asmntActionPerformed
        // TODO add your handling code here:
        adAsUp=new AdministratorAssignmentUpdate();
        adAsUp.setVisible(true);
        adAsUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_asmntActionPerformed

    private void lecHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecHActionPerformed
        // TODO add your handling code here:
        adLecUp=new AdministratorLecturerUpdate();
        adLecUp.setVisible(true);
        adLecUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_lecHActionPerformed

    private void insHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insHActionPerformed
        // TODO add your handling code here:
        adInUp=new AdministratorInstructorUpdate();
        adInUp.setVisible(true);
        adInUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_insHActionPerformed

    private void subBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtn1ActionPerformed

    private void subBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtn2ActionPerformed
        // TODO add your handling code here:
        adCsUp=new AdministratorCourseUpdate();
        adCsUp.setVisible(true);
        adCsUp.setLocationRelativeTo(null);
    }//GEN-LAST:event_subBtn2ActionPerformed

    private void subBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtn3ActionPerformed
        // TODO add your handling code here:
        adLoc=new AdministratotLocationUpdate();
        adLoc.setVisible(true);
        adLoc.setLocationRelativeTo(null);
    }//GEN-LAST:event_subBtn3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asmnt;
    private javax.swing.JButton insH;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lecH;
    private javax.swing.JButton pH;
    private javax.swing.JButton subBtn;
    private javax.swing.JButton subBtn1;
    private javax.swing.JButton subBtn2;
    private javax.swing.JButton subBtn3;
    private javax.swing.JButton tA;
    private javax.swing.JButton uH;
    // End of variables declaration//GEN-END:variables
}
