/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controller.DepartmentController.searchDepartment;
import Model.Department;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Asitha
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    public static Home hm;
    public static UndergraduateLogin unLogin;
    public static PostgraduateLogin postLogin;
    public static InstructorLogin insLogin;
    public static AdministratorLogin adminLogin;
    public static LecturerLogin lecLogin;
    
    public static Department dep= new Department();
    public static String depid;
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectLec = new javax.swing.JButton();
        selectIns = new javax.swing.JButton();
        selectAdmin = new javax.swing.JButton();
        underBtn = new javax.swing.JButton();
        selecPos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        selectDepartment = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NSBM");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        selectLec.setBackground(new java.awt.Color(255, 255, 255));
        selectLec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lec.png"))); // NOI18N
        selectLec.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                selectLecMouseMoved(evt);
            }
        });
        selectLec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectLecMouseExited(evt);
            }
        });
        selectLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLecActionPerformed(evt);
            }
        });

        selectIns.setBackground(new java.awt.Color(255, 255, 255));
        selectIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/instruc.png"))); // NOI18N
        selectIns.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                selectInsMouseMoved(evt);
            }
        });
        selectIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInsActionPerformed(evt);
            }
        });

        selectAdmin.setBackground(new java.awt.Color(255, 255, 255));
        selectAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N
        selectAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                selectAdminMouseMoved(evt);
            }
        });
        selectAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdminActionPerformed(evt);
            }
        });

        underBtn.setBackground(new java.awt.Color(255, 255, 255));
        underBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/under.png"))); // NOI18N
        underBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                underBtnMouseMoved(evt);
            }
        });
        underBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underBtnActionPerformed(evt);
            }
        });

        selecPos.setBackground(new java.awt.Color(255, 255, 255));
        selecPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/post.png"))); // NOI18N
        selecPos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                selecPosMouseMoved(evt);
            }
        });
        selecPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecPosActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/visitors.png"))); // NOI18N

        selectDepartment.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        selectDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "School of Business", "School of Computing", "School of Engineering" }));
        selectDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(underBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selectAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(selectLec, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selectIns, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selecPos, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(selectDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selecPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectIns, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectLec, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(underBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLecActionPerformed
        // TODO add your handling code here:
        if(getSelectDepartment().getSelectedItem().equals("Select Department")){
            JOptionPane.showMessageDialog(rootPane, "Please Select Department");
        }
        else{
            this.setVisible(false);
            lecLogin=new LecturerLogin();
            lecLogin.setVisible(true);
            lecLogin.setLocationRelativeTo(null);
            String department=(String)hm.getSelectDepartment().getSelectedItem();
            try {
                dep=searchDepartment(department);
                depid=dep.getDepartmentID();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
                
        
    }//GEN-LAST:event_selectLecActionPerformed

    private void selectLecMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLecMouseMoved
        selectLec.setToolTipText("Lecturer Login");
    }//GEN-LAST:event_selectLecMouseMoved

    private void selectLecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLecMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selectLecMouseExited

    private void selectAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAdminActionPerformed
        // TODO add your handling code here:
        if(getSelectDepartment().getSelectedItem().equals("Select Department")){
            JOptionPane.showMessageDialog(rootPane, "Please Select Department");
        }
        else{
        this.setVisible(false);
        adminLogin=new AdministratorLogin();
        adminLogin.setVisible(true);
        adminLogin.setLocationRelativeTo(null);
        String department=(String)hm.getSelectDepartment().getSelectedItem();
            try {
                dep=searchDepartment(department);
                depid=dep.getDepartmentID();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_selectAdminActionPerformed

    private void underBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underBtnActionPerformed
        // TODO add your handling code here:
        if(getSelectDepartment().getSelectedItem().equals("Select Department")){
            JOptionPane.showMessageDialog(rootPane, "Please Select Department");
        }
        else{
        this.setVisible(false);
        unLogin=new UndergraduateLogin();
        unLogin.setVisible(true);
        unLogin.setLocationRelativeTo(null);
        String department=(String)hm.getSelectDepartment().getSelectedItem();
            try {
                dep=searchDepartment(department);
                depid=dep.getDepartmentID();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_underBtnActionPerformed

    private void selectInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInsActionPerformed
        // TODO add your handling code here:
        if(getSelectDepartment().getSelectedItem().equals("Select Department")){
            JOptionPane.showMessageDialog(rootPane, "Please Select Department");
        }
        else{
        this.setVisible(false);
        insLogin=new InstructorLogin();
        insLogin.setVisible(true);
        insLogin.setLocationRelativeTo(null);
        String department=(String)hm.getSelectDepartment().getSelectedItem();
            try {
                dep=searchDepartment(department);
                depid=dep.getDepartmentID();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_selectInsActionPerformed

    private void selecPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecPosActionPerformed
        // TODO add your handling code here:
        if(getSelectDepartment().getSelectedItem().equals("Select Department")){
            JOptionPane.showMessageDialog(rootPane, "Please Select Department");
        }
        else{
        this.setVisible(false);
        postLogin=new PostgraduateLogin();
        postLogin.setVisible(true);
        postLogin.setLocationRelativeTo(null);
        String department=(String)hm.getSelectDepartment().getSelectedItem();
            try {
                dep=searchDepartment(department);
                depid=dep.getDepartmentID();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_selecPosActionPerformed

    private void underBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_underBtnMouseMoved
        // TODO add your handling code here:
        underBtn.setToolTipText("Undergraduate Login");
    }//GEN-LAST:event_underBtnMouseMoved

    private void selectAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectAdminMouseMoved
       selectAdmin.setToolTipText("Administrator Login");
    }//GEN-LAST:event_selectAdminMouseMoved

    private void selecPosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecPosMouseMoved
        // TODO add your handling code here:
        selecPos.setToolTipText("Postgraduate Login");
    }//GEN-LAST:event_selecPosMouseMoved

    private void selectInsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectInsMouseMoved
       selectIns.setToolTipText("Instructor Login");
    }//GEN-LAST:event_selectInsMouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
       
    }//GEN-LAST:event_jPanel1MouseMoved

    private void selectDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                hm=new Home();
                hm.setVisible(true);
                hm.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selecPos;
    private javax.swing.JButton selectAdmin;
    private javax.swing.JComboBox<String> selectDepartment;
    private javax.swing.JButton selectIns;
    private javax.swing.JButton selectLec;
    private javax.swing.JButton underBtn;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getSelectDepartment() {
        return selectDepartment;
    }

    public void setSelectDepartment(javax.swing.JComboBox<String> selectDepartment) {
        this.selectDepartment = selectDepartment;
    }

    
}
